import localFont from "next/font/local";
import "./globals.css";
// import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Header from "@/features/Header/Header";
import FeatureBenefits from "@/features/BenefitsSection/BenefitsSection";
import Footer from "@/features/Footer/Footer";
import Topbar from "@/features/Header/components/Topbar";
import Searchbar from "@/features/Header/components/Searchbar";
import NavbarYeni from "@/features/Header/Navbar/Navbar";
import Providers from "@/common/store/Providers";
// import NavbarYeni from "@/features/Header/Navbar/Navbar";

// config.autoAddCss = false;

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header /> */}
        <Providers>
          <Topbar />
          <Searchbar />
          <NavbarYeni />
          {children}
          <FeatureBenefits />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
